// This file was auto-generated by Fern from our API Definition.

package api

type GetCrmV3ObjectsContactsContactIdGetByIdRequest struct {
	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties []*string `json:"-" url:"properties,omitempty"`
	// A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored.
	PropertiesWithHistory []*string `json:"-" url:"propertiesWithHistory,omitempty"`
	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations []*string `json:"-" url:"associations,omitempty"`
	// Whether to return only results that have been archived.
	Archived *bool `json:"-" url:"archived,omitempty"`
}

type GetCrmV3ObjectsContactsGetPageRequest struct {
	// The maximum number of results to display per page.
	Limit *int `json:"-" url:"limit,omitempty"`
	// The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results.
	After *string `json:"-" url:"after,omitempty"`
	// A comma separated list of the properties to be returned in the response. If any of the specified properties are not present on the requested object(s), they will be ignored.
	Properties []*string `json:"-" url:"properties,omitempty"`
	// A comma separated list of the properties to be returned along with their history of previous values. If any of the specified properties are not present on the requested object(s), they will be ignored. Usage of this parameter will reduce the maximum number of objects that can be read by a single request.
	PropertiesWithHistory []*string `json:"-" url:"propertiesWithHistory,omitempty"`
	// A comma separated list of object types to retrieve associated IDs for. If any of the specified associations do not exist, they will be ignored.
	Associations []*string `json:"-" url:"associations,omitempty"`
	// Whether to return only results that have been archived.
	Archived *bool `json:"-" url:"archived,omitempty"`
}

type SimplePublicObjectInput struct {
	Properties map[string]string `json:"properties,omitempty" url:"-"`
}
