// This file was auto-generated by Fern from our API Definition.

package api

type BatchInputSimplePublicObjectId struct {
	Inputs []*SimplePublicObjectId `json:"inputs,omitempty" url:"-"`
}

type BatchInputSimplePublicObjectInputForCreate struct {
	Inputs []*SimplePublicObjectInputForCreate `json:"inputs,omitempty" url:"-"`
}

type BatchReadInputSimplePublicObjectId struct {
	// Whether to return only results that have been archived.
	Archived              *bool                   `json:"-" url:"archived,omitempty"`
	PropertiesWithHistory []string                `json:"propertiesWithHistory,omitempty" url:"-"`
	IdProperty            *string                 `json:"idProperty,omitempty" url:"-"`
	Inputs                []*SimplePublicObjectId `json:"inputs,omitempty" url:"-"`
	Properties            []string                `json:"properties,omitempty" url:"-"`
}

type BatchInputSimplePublicObjectBatchInput struct {
	Inputs []*SimplePublicObjectBatchInput `json:"inputs,omitempty" url:"-"`
}
