// This file was auto-generated by Fern from our API Definition.

package api

type PublicGdprDeleteInput struct {
	IdProperty *string `json:"idProperty,omitempty" url:"-"`
	ObjectId   string  `json:"objectId" url:"-"`
}
