// This file was auto-generated by Fern from our API Definition.

package api

type PublicMergeInput struct {
	ObjectIdToMerge string `json:"objectIdToMerge" url:"-"`
	PrimaryObjectId string `json:"primaryObjectId" url:"-"`
}
